{
  powers: ["Jump", "Beerpong"];
  realName: "Tobbi";
  alias: "Lola";
  origin: "Island";
  weakness: "boxing";
  active: false;
  isEvil: true;
  height: 168;
  birthday: {
    day: 14;
    month: 7;
    year: 1998;
  }

  image: "https://www.pexels.com/photo/people-wearing-spider-man-adult-costume-walking-on-train-station-2859016/";
}

/////////////////////////////////////////////////////

[
  {
    powers: ["Design", "Gaming"],
    realName: "Ceva",
    alias: "Godcille",
    origin: "Nødebo",
    weaknesses: ["Code", "Alcohol"],
    active: true,
    isEvil: true,
    height: 168,
    birtday: {
      day: 22,
      month: 6,
      year: 1994,
    },
    image: "https://www.pexels.com/da-dk/foto/kvinde-leg-teknologi-spil-6499009/",
  },
  {
    powers: ["Beer", "Sleep"],
    realName: "Anton Rieo",
    alias: "The Riel One",
    origin: "Herlev",
    weaknesses: ["Vegetable", "water"],
    active: true,
    isEvil: true,
    height: 193,
    birtday: {
      day: 3,
      month: 7,
      year: 1997,
    },
    image: "https://www.pexels.com/da-dk/foto/mand-person-styrke-fitness-38630",
  },
  {
    powers: ["Fly", "Invisiblity"],
    realName: "Mini",
    alias: "Mad Manta",
    origin: "Fiji",
    weaknesses: ["Spiders", "Small talk"],
    active: true,
    isEvil: false,
    height: 155,
    birtday: {
      day: 11,
      month: 8,
      year: 1997,
    },
    image: "https://www.pexels.com/photo/manta-ray-in-close-up-shot-5547013/",
  },
  {
    powers: ["music", "football"],
    realName: "August",
    alias: "Dipsy",
    origin: "Hellerup",
    weaknesses: ["games", "hovedspring"],
    active: true,
    isEvil: true,
    height: 183,
    birtday: {
      day: 11,
      month: 6,
      year: 2001,
    },
    image: "https://picsum.photos/200/300",
  },
  {
    powers: ["invisibility", "flying"],
    realname: "John",
    alias: "Bobby",
    origin: "tatooine",
    weakness: "aim",
    active: true,
    isEvil: false,
    height: 182,
    birthday: {
      day: 15,
      month: 6,
      year: 1993,
    },
    image: "https://picsum.photos/id/420/200/300",
  },
  {
    powers: ["Eating", "Beer"],
    realName: "Vera",
    alias: "longlegs",
    origin: "Island",
    weaknesses: ["drawing", "flying"],
    active: true,
    isEvil: false,
    height: 164,
    birtday: {
      day: 4,
      month: 12,
      year: 1996,
    },
    image: "https://images.pexels.com/photos/6138297/pexels-photo-6138297.jpeg?auto=compress&cs=tinysrgb&w=1600",
  },
  {
    powers: ["Design", "cleaning"],
    realName: "Cody",
    alias: "CD",
    origin: "København",
    weaknesses: ["beeing social", "darkness"],
    active: true,
    isEvil: true,
    height: 167,
    birtday: {
      day: 2,
      month: 4,
      year: 2001,
    },
    image: "https://unsplash.com/photos/niE_3XB02OQ",
  },
  {
    powers: ["Wine", "Pistols"],
    realName: "Pablo",
    alias: "Don Pablo",
    origin: "Italy",
    weaknesses: ["Bad food", "Cigarets"],
    active: true,
    isEvil: true,
    height: 172,
    birtday: {
      day: 5,
      month: 7,
      year: 1948,
    },
    image: "https://www.pexels.com/da-dk/foto/mode-mand-person-maend-1933873/",
  },
  {
    alias: "GDPR-man",
    powers: "Inconvinience",
    realName: "Unknown",
    isEvil: true,
    active: true,
    birthday: {
      day: 1,
      month: 6,
      year: 98,
    },
    image: "https://www.jackie-phillip.dk/wp-content/uploads/2020/01/gdpr-regler-eu-konsulent.jpg",
  },
  {
    powers: ["Strong", "Fashion sense", "Green"],
    realName: "Shrek",
    alias: "The Swamp Troll",
    origin: "The Swamp",
    weaknesses: ["Fiona", "Intruders"],
    active: true,
    isEvil: true,
    height: 246,
    birthday: {
      day: 24,
      month: 12,
      year: 1089,
    },
    image: "https://i.seadn.io/gae/2hDpuTi-0AMKvoZJGd-yKWvK4tKdQr_kLIpB_qSeMau2TNGCNidAosMEvrEXFO9G6tmlFlPQplpwiqirgrIPWnCKMvElaYgI-HiVvXc?auto=format&dpr=1&w=1000",
  },
  {
    powers: ["Happy", "Tequila"],
    realName: "Carl",
    alias: "ZARL",
    origin: "Aarhus",
    weaknesses: ["Very Shy", "Very Weird"],
    active: true,
    isEvil: true,
    height: 190,
    birtday: {
      day: 11,
      month: 9,
      year: 1998,
    },
    image: "https://pixabay.com/da/vectors/smiley-hum%C3%B8rikon-lykkelig-ansigt-1635449/",
  },
  {
    powers: ["Invisible", "teleporting"],
    realName: "David",
    alias: "HoudiniLinguini",
    origin: "Copenhagen",
    weaknesses: ["Too fast", "Too strong"],
    active: true,
    isEvil: true,
    height: 185,
    birtday: {
      day: 29,
      month: 9,
      year: 2001,
    },
    image: "https://images.pexels.com/photos/6138297/pexels-photo-6138297.jpeg?auto=compress&cs=tinysrgb&w=1600",
  },
  {
    powers: ["Jump", "Beerpong"],
    realName: "Tobbi",
    alias: "Lola",
    origin: "Island",
    weakness: "boxing",
    active: false,
    isEvil: true,
    height: 168,
    birthday: {
      day: 14,
      month: 7,
      year: 1998,
    },
    image: "https://www.pexels.com/photo/people-wearing-spider-man-adult-costume-walking-on-train-station-2859016/",
  },
  {
    powers: ["JS", "Beer"],
    realName: "Superman",
    origin: "Hillerød",
    weaknesses: ["JS", "drinks"],
    active: true,
    isEvil: false,
    height: 198,
    birtday: {
      day: 23,
      month: 8,
      year: 2001,
    },
    image: "https://img.freepik.com/premium-photo/achievement-business-goal-success-concept_31965-2303.jpg?size=626&ext=jpg",
  },
  {
    powers: ["Fly", "Invisible", "Mindreading", "Superstrenght"],
    realName: "Timon",
    alias: "Bodybuilder",
    origin: "Mars",
    weaknesses: ["Alcohol", "Junkfood"],
    active: true,
    isEvil: false,
    height: 200,
    birtday: {
      day: 24,
      month: 12,
      year: 1996,
    },
    image: "https://images.pexels.com/photos/3180275/pexels-photo-3180275.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    powers: ["flying", "Loud Screaming"],
    realName: "Laila",
    alias: "YoloQueen",
    origin: "Roskilde",
    weaknesses: ["Rain", "Modvind"],
    active: true,
    isEvil: true,
    height: 172,
    birtday: {
      day: 27,
      month: 4,
      year: 2000,
      image: "https://www.pexels.com/da-dk/foto/himmel-person-flyve-sol-384498/",
    },
  },
  {
    powers: ["Boombs", "Motercycles"],
    realName: "Annie",
    alias: "The Bike Lady",
    origin: "San Fransico",
    weaknesses: ["Electronics", "redWine"],
    active: true,
    isEvil: true,
    height: 162,
    birtday: {
      day: 4,
      month: 12,
      year: 1953,
    },
    image: "https://img.freepik.com/premium-photo/stylish-fashionable-elderly-happy-woman-tattoos-smiles-onblack-background-generative-ai_118086-7838.jpg?w=1800",
  },
  {
    powers: ["adorable", "strong"],
    realName: "Tut",
    alias: "birb",
    origin: "Sjælland",
    weaknesses: ["code", "krispy kreme doughnuts"],
    active: true,
    isEvil: true,
    height: 10,
    birtday: {
      day: 31,
      month: 5,
      year: 2001,
    },
    image: "https://images.pexels.com/photos/162137/duckling-birds-yellow-fluffy-162137.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    powers: ["ild", "våben"],
    realName: "Maria",
    alias: "Bibli",
    origin: "Holland",
    weaknesses: ["bobler", "bøger"],
    active: true,
    isEvil: true,
    height: 168,
    birtday: {
      day: 14,
      month: 2,
      year: 1990,
    },
    image: "https://images.pexels.com/photos/162520/farmer-man-shepherd-dog-162520.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    powers: ["Drinking", "driving drunk"],
    realName: "Olaf",
    alias: "Count O",
    origin: "Brede",
    weaknesses: ["Not drinking", "tequila"],
    active: true,
    isEvil: false,
    height: 152,
    birtday: {
      day: 5,
      month: 19,
      year: 1995,
    },
    image: "https://images.pexels.com/photos/3823540/pexels-photo-3823540.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    powers: ["strength", "dancing "],
    realName: "Olaf",
    alias: "Frosty",
    origin: "home",
    weaknesses: ["spiders", "mornings"],
    active: true,
    isEvil: true,
    height: 40,
    birthday: {
      day: 4,
      month: 5,
      year: 3005,
    },
    image: "https://www.pexels.com/photo/snowman-holding-shovel-3334473/",
  },
  {
    powers: ["Flyve", "Power of the night"],
    realName: "Bertha",
    alias: "Bertha the great",
    origin: "Månen",
    weaknesses: ["vindstød", "sol"],
    active: true,
    isEvil: true,
    height: 150,
    birtday: {
      day: 1,
      month: 1,
      year: 13,
    },
    image: "https://imgur.com/bgGOaw4",
  },
  {
    powers: ["Height", "Reach"],
    realName: "Sven Åkeson",
    alias: "Lesther Vester",
    origin: "Herlev",
    weaknesses: ["Basketball"],
    active: true,
    isEvil: false,
    height: 194,
    birtday: {
      day: 28,
      month: 5,
      year: 1997,
    },
    image: "https://imgur.com/a/xfwcMrD",
  },
  {
    powers: ["loverboy"],
    realName: "Miski",
    alias: "lingini Sith",
    origin: "afd.12",
    weaknesses: ["simp"],
    active: true,
    isEvil: true,
    height: 175,
    birtday: {
      day: 5,
      month: 12,
      year: 2000,
    },
    image: "https://www.pexels.com/da-dk/foto/hoved-krybdyr-skal-langsom-17920409/",
  },
  {
    powers: ["strong", "fast", "fire"],
    realName: "Lander",
    alias: "FireGirl",
    origin: "Moon",
    weaknesses: ["confused", "hungry"],
    active: true,
    isEvil: true,
    height: 176,
    birtday: {
      day: 30,
      month: 10,
      year: 2015,
    },
    image: "https://www.pexels.com/da-dk/foto/rod-pige-drom-jakke-5560061/",
  },
  {
    powers: ["Superspeed", "Flight"],
    realName: "Kenneth",
    alias: "Sir Senpai",
    origin: "Denmark",
    weaknesses: ["Maplesyrup", "Short Term Memory"],
    active: true,
    isEvil: false,
    height: 183,
    birtday: {
      day: 7,
      month: 8,
      year: 1991,
    },
    image: "Photo by daniyal ghanavati from Pexels: https://www.pexels.com/photo/shallow-focus-photography-of-black-and-green-turtle-109892/",
  },
  {
    powers: ["Power to control solar energy, channeling it into devastating solar flares and using it for flight"],
    realName: "Soleil Sun",
    alias: "Solara Songbird",
    origin: "Luminora",
    weaknesses: ["Darkness", "Night"],
    active: true,
    isEvil: false,
    height: 156,
    birtday: {
      day: 7,
      month: 7,
      year: 2002,
    },
    image: "https://i.pinimg.com/originals/26/64/da/2664da23f93ac1c9f1f94fa7a2583260.jpg",
  },
  {
    powers: ["flyve", "tankelæser"],
    realName: "Emma Jensen",
    alias: "Shadowstrike",
    origin: "Italien",
    weaknesses: ["Pasta", "Twix"],
    active: true,
    isEvil: false,
    height: 160,
    birtday: {
      day: 14,
      month: 6,
      year: 1999,
    },
    image: "https://www.pexels.com/da-dk/foto/portraet-sjov-superhelt-halloween-6080351/",
  },
  {
    powers: ["HBO max", "Gin Hass", "Invisible"],
    realName: "Bobby Blue",
    alias: "Supermask",
    origin: "Kastrup",
    weakness: ["Javascript", "Spiders"],
    active: true,
    isEvil: false,
    height: 165,
    birthday: {
      day: 18,
      month: 9,
      year: 2000,
    },
    image: "https://www.pexels.com/da-dk/foto/sodt-barn-superhelt-maske-6202803/",
  },
  {
    powers: ["LL, Run"],
    realName: "Sky",
    alias: "Raccon",
    origin: "Rome",
    weaknesses: "Metal",
    active: "true",
    isEvil: "true",
    height: "172",
    birthday: {
      day: 19,
      month: 7,
      year: 1998,
    },
    image: "https://youtu.be/2KcNm6ftD7g?si=rvX9GRx7n3afs-F1",
  },
  {
    powers: ["usynlig", "elastisk"],
    realName: "livzino",
    alias: "livlicious",
    origin: "København",
    weaknesses: ["mel", "æg"],
    active: true,
    isEvil: true,
    height: 175,
    birtday: {
      day: 27,
      month: 8,
      year: 2000,
    },
    image: "https://picsum.photos/id/63/367/267",
  },
  {
    powers: ["Tanning", "Cooking"],
    realName: "Marty",
    alias: "Small Cat",
    origin: "Los Angeles",
    weaknesses: ["JS", "Dancing"],
    active: true,
    isEvil: true,
    height: 173,
    birtday: {
      day: 26,
      month: 4,
      year: 1997,
    },
    image: "https://images.pexels.com/photos/6138297/pexels-photo-6138297.jpeg?auto=compress&cs=tinysrgb&w=1600",
  },
  {
    powers: ["Flying", "Fast"],
    realName: "NootNoot",
    alias: "Nutellamark",
    origin: "Rødovre",
    weaknesses: ["night", "food"],
    active: true,
    isEvil: true,
    height: 179,
    birtday: {
      day: 12,
      month: 11,
      year: 2001,
    },
    image: "https://images.pexels.com/photos/4048/strength-strong-toy-action-figure.jpg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    powers: ["flying", "magic"],
    realName: "Mie",
    alias: "Mona",
    origin: "Denmark",
    weaknesses: ["men"],
    active: true,
    isEvil: true,
    height: 210,
    birthday: {
      day: 1,
      month: 1,
      year: 1000,
    },
    image: "https://www.pexels.com/da-dk/foto/mand-jakke-portraet-kostume-4330960/",
  },
  {
    realName: "Michael Thorne",
    powers: ["Bass-guitar", "Voice-boom", "Thunderschock"],
    alias: "ThunderBear",
    origin: "Jutlandia",
    weaknesses: ["Coffee", "Bad vibes"],
    active: true,
    isEvil: false,
    height: 210,
    birtday: {
      day: 11,
      month: 11,
      year: 1911,
    },
    image: "https://images.unsplash.com/photo-1531907700752-62799b2a3e84?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
  },
  {
    powers: ["invisibility"],
    realName: "Molly Walthers",
    alias: "MoonWolf",
    origin: "The moon",
    weakness: ["Sun", "Spiders"],
    active: true,
    isEvil: true,
    height: 175,
    birthday: {
      day: 13,
      month: 2,
      year: 1998,
    },
    image: "https://www.pexels.com/photo/portrait-of-woman-in-face-paint-with-her-wolf-11739206/",
  },
  {
    powers: ["curious", "helpful"],
    realName: "Nana",
    alias: "unknown",
    origin: "Germany",
    weaknesses: ["Javascript", "Photoshop", "animation"],
    active: true,
    isEvil: false,
    height: 172,
    birthday: {
      day: 24,
      month: 3,
      year: 2001,
    },
    image: "images.pexels.com/photos/16142799/pexels-photo-16142799/free-photo-of-gade-fortov-vinduer-gyde.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    powers: ["Money", "Intellectual"],
    realName: "Ole",
    alias: "Kurt Thorsen",
    origin: "Denmark",
    weaknesses: ["Prison", "Hammer"],
    active: true,
    isEvil: true,
    height: 146,
    birtday: {
      day: 16,
      month: 3,
      year: 1988,
    },
    image: "https://images.pexels.com/photos/3824771/pexels-photo-3824771.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    powers: ["fly", "sing"],
    realName: "Mona",
    alias: "MonaOna",
    origin: "LT",
    weaknesses: ["Design", "Beer"],
    active: true,
    isEvil: true,
    height: 165,
    birtday: {
      day: 9,
      month: 1,
      year: 1988,
    },
    image: "https://images.pexels.com/photos/6138297/pexels-photo-6138297.jpeg?auto=compress&cs=tinysrgb&w=1600",
  },
  {
    powers: ["Sleeping", "Laying Down"],
    realName: "Orla",
    alias: "Orla Frøsnapper",
    origin: "Slagelse",
    weaknesses: ["Being Awake", "Standing Up"],
    active: true,
    isEvil: true,
    height: 205,
    birtday: {
      day: 25,
      month: 8,
      year: 1969,
    },
    image: "https://i.pinimg.com/originals/8a/47/9f/8a479fbcd46aad65eddb8344135d1032.jpg",
  },
  {
    powers: ["Rest", "Beer", "Watching television"],
    realName: "Los Pedro ",
    alias: "Double p",
    origin: "none",
    weaknesses: ["programming", "paying attention"],
    active: true,
    isEvil: false,
    height: 185,
    birtday: {
      day: 24,
      month: 11,
      year: 1901,
    },
    image: "https://images.pexels.com/photos/3687770/pexels-photo-3687770.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    powers: ["redbull", "tennis"],
    realName: "brian",
    alias: "master tennis",
    origin: "nørrebro",
    weaknesses: ["girls", "wine"],
    active: true,
    isEvil: true,
    height: 140,
    birtday: {
      day: 8,
      month: 6,
      year: 2005,
    },
    image: "https://www.pexels.com/da-dk/foto/by-mand-jeans-farverig-5339952/",
  },
  {
    power: ["Crochet", "Programming"],
    realName: "Violet",
    alias: "Crochet hero",
    origin: "Swenden",
    weaknesses: ["Design", "Organisation"],
    active: false,
    isEvil: false,
    height: 165,
    birthday: {
      day: 1,
      mounth: 2,
      year: 2000,
    },
    image: "https://www.pexels.com/da-dk/foto/kvinde-sidde-portraet-taenke-17997543/",
  },
  {
    powers: ["Monkey", "Banana"],
    realName: "Svend Åge Pedersen",
    alias: "Monkeeman",
    origin: "Taastrup",
    weaknesses: ["Beers"],
    active: true,
    isEvil: true,
    height: 190,
    birtday: {
      day: 28,
      month: 6,
      year: 1934,
    },
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5uwS3MEjR081iUV6uaP2QTpyvXiDL-k4hsg&usqp=CAU",
  },
  {
    powers: ["Firebreath", "Flying", "Superspeed", "Supervision"],
    realName: "Shyv",
    alias: "Slyvanna",
    origin: "Pluto",
    weaknesses: ["Beer", ""],
    active: true,
    isEvil: true,
    height: 292,
    birtday: {
      day: 14,
      month: 2,
      year: 1278,
    },
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.oneesports.gg%2Fleague-of-legends%2Fshyvana-gets-a-fearsome-dragon-design-in-her-new-ruined-skin%2F&psig=AOvVaw3vdfn-N5G6puzBwXBakTeG&ust=1693046571184000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCIifjYzQ94ADFQAAAAAdAAAAABAE",
  },
  {
    powers: [],
    realName: "Bo",
    alias: "Krøllebølle",
    origin: "Bornholm",
    weakness: ["icecream", "sunshine"],
    active: true,
    isEvil: true,
    height: 120,
    birthday: {
      day: 24,
      month: 12,
      year: 1600,
    },
    image: "https://www.pexels.com/da-dk/foto/argang-bord-gave-design-4007776/",
  },
  {
    powers: ["fighting", "laser"],
    realName: "Becky Black",
    alias: "Black Diphylleia",
    origin: "New York",
    weaknesses: ["teddy bear", "bees"],
    active: false,
    isEvil: true,
    height: 154,
    birthday: {
      day: 11,
      month: 1,
      year: 2001,
    },
    image: "https://images.pexels.com/photos/11794335/pexels-photo-11794335.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    powers: ["JS", "Beer"],
    realName: "Joe",
    alias: "Joe not the juice",
    origin: "Osterbro",
    weaknesses: ["Design", "Juice"],
    active: true,
    isEvil: true,
    height: 174,
    birtday: {
      day: 24,
      month: 4,
      year: 2001,
    },
    image: "https://images.pexels.com/photos/3196887/pexels-photo-3196887.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    powers: ["control over the moon's phases, manipulate tides, eclipses, and lunar energy to unleash havoc on your enemies."],
    realName: "Jazmin Night",
    alias: "Lunar Eclipse",
    origin: "Luminora",
    weaknesses: ["day, brightness"],
    active: true,
    isEvil: true,
    height: 162,
    birtday: {
      day: 1,
      month: 1,
      year: 2001,
    },
    image: "https://i.pinimg.com/originals/22/f8/c2/22f8c249a9a593063f1f640b3b873b36.jpg",
  },
];
